import {
  getSchedulesForExport,
  generateExcel,
  generatePDF,
} from "../services/scheduleExportService.js";

export const exportSchedule = async (
  req,
  res
) => {
  try {
    const {
      week = "ALL",
      month,
      year,
      format,
    } = req.query;

    if (!month || !year) {
      return res.status(400).json({
        message:
          "Month and year are required.",
      });
    }

    if (
      !["pdf", "excel", "both"].includes(
        format
      )
    ) {
      return res.status(400).json({
        message:
          "Format must be pdf, excel or both.",
      });
    }

    const schedules =
      await getSchedulesForExport({
        week,
        month,
        year,
      });

    if (schedules.length === 0) {
      return res.status(404).json({
        message:
          "No schedules found for the selected period.",
      });
    }

    // ------------------------------------------------
    // PDF
    // ------------------------------------------------

    if (format === "pdf") {
      const buffer =
        await generatePDF({
          schedules,
          month,
          year,
          week,
        });

      res.setHeader(
        "Content-Type",
        "application/pdf"
      );

      res.setHeader(
        "Content-Disposition",
        `attachment; filename="NPBC-Schedule-${year}-${month}-${week}.pdf"`
      );

      return res.send(buffer);
    }

    // ------------------------------------------------
    // Excel
    // ------------------------------------------------

    if (format === "excel") {
      const buffer =
        await generateExcel({
          schedules,
          month,
          year,
          week,
        });

      res.setHeader(
        "Content-Type",
        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
      );

      res.setHeader(
        "Content-Disposition",
        `attachment; filename="NPBC-Schedule-${year}-${month}-${week}.xlsx"`
      );

      return res.send(buffer);
    }

    // ------------------------------------------------
    // Both
    // ------------------------------------------------

    if (format === "both") {
      return res.status(400).json({
        message:
          "Please select PDF or Excel separately. Both files will be generated by the frontend.",
      });
    }
  } catch (error) {
    console.error(
      "EXPORT SCHEDULE ERROR:",
      error
    );

    res.status(500).json({
      message:
        error.message ||
        "Unable to export schedule.",
    });
  }
};